# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

# Triggers the workflow on push or pull request events (on every branch)
on:
  push:
    branches: [ master, develop]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: app/build/test-results/test/
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: swagger.json
        path: app/export/swagger.json
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: swagger-coverage-report
        path: |
          app/swagger-coverage-results.json
          app/swagger-coverage-report.html
